### ISSUE TITLE
HttpException objects causing errors due to having been constructed with non-string msg

### ISSUE THREAD

**Issue by grahambell** [opencadc/cadctools#175]
HttpException's `__str__` method sometimes encounters an error when what it tries to return isn't a string, i.e. if self.msg is defined but isn't a string.   For example:

```
File ".../vos/vos.py", line 1124, in read
    if 'SSLV3_ALERT_CERTIFICATE_EXPIRED' in str(http_exception):
TypeError: __str__ returned non-string (type ConnectionError)
```

It looks like `cadcutils.net.ws` constructs HttpException objects with the original exception as the first parameter (should be `msg`) instead of the second.

**Comment by andamian** [comment]
@grahambell - Fixed now. Thanks for reporting. I've had the fix on my local branch for a while and was trying to bundle it with other things but it's becoming annoying so I did a quick release (`cadcutils - 1.2.4`)
