### ISSUE TITLE
_get_url in BaseWsClient uses and extra '/'

### ISSUE THREAD

**Issue by andamian** [opencadc/cadctools#18]
When the resource is of the (standardID, '') the function returns the path with a '/' at the end. That does not work if the path is used with a query string '?'

**Comment by ijiraq** [comment]
I think we need to allow the 2nd member of the tuple to be None and then only do the join if one member is not None.

Why is it a tuple?

JJ

**Comment by andamian** [comment]
@ijiraq : That's what the solution is. 

The argument is meant to pass the path of the url and when the path is known that works fine. Sometimes however the client only has the path relative to a feature and this is when the tuple is used: first part identifies the feature and the second the relative path. Do you have a different solution in mind?

**Comment by andamian** [comment]
Fixed and released
